/*
 * Album Store API
 *
 * CS6650 Fall 2023
 *
 * API version: 1.0.0
 * Contact: i.gorton@northeasern.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ImageMetaData struct {

	AlbumID string `json:"albumID,omitempty"`

	ImageSize string `json:"imageSize,omitempty"`
}
